### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/text/StringsKt

### ISSUE THREAD

**Issue by dene14** [teambition/kafka-connect-mongo#3]
Hello, I've tried to build mongo connector from tag 1.3.0
And having issues with it:
On first attempt when I've tried to put configuration through API it thrown this error:
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

after some googling I've figured out that kotlin-runtime.jar should be available in classpath, I did so and now I'm having subj:
java.lang.NoClassDefFoundError: kotlin/text/StringsKt
at org.apache.kafka.connect.mongo.MongoSourceConnector.taskConfigs(MongoSourceConnector.kt:47)
at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:230)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:967)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:918)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$800(DistributedHerder.java:101)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:931)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:928)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:250)
at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:200)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

Please advise. Any help higly appreciated (maybe I need a list of jars to include into classpath or something else)...
Many thanks in advance!

**Comment by sailxjx** [comment]
use `./gradlew distTar`, unarchive the tarball, then add the directory in your class path.

**Comment by dene14** [comment]
yes, sorry, I've missed an archive in distribution directory, all good. Close this

Thank you!
