### ISSUE TITLE
Missing required import setting for Mongo source

### ISSUE THREAD

**Issue by sabinthomas** [teambition/kafka-connect-mongo#7]
Running against release [v1.4.1] (https://github.com/teambition/kafka-connect-mongo/releases/tag/1.4.1), the config file is missing 'initial.import' setting.

```
[2017-11-10 15:42:21,654] INFO Instantiated connector mongo-source-connector with version 0.10.2.1 of type org.apache.kafka.connect.mongo.MongoSourceConnector (org.apache.kafka.connect.runtime.Worker:176)
[2017-11-10 15:42:21,661] ERROR Error while starting connector mongo-source-connector (org.apache.kafka.connect.runtime.WorkerConnector:108)
org.apache.kafka.connect.errors.ConnectException: Missing initial.import config
	at org.apache.kafka.connect.mongo.MongoSourceConnector.getRequiredProp(MongoSourceConnector.kt:74)
	at org.apache.kafka.connect.mongo.MongoSourceConnector.start(MongoSourceConnector.kt:39)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:178)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:250)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:164)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
```

**Comment by sabinthomas** [comment]
@sailxjx , Created pull request = #8 for your review.
