### ISSUE TITLE
Logging Error

### ISSUE THREAD

**Issue by harshsp31** [teambition/kafka-connect-mongo#9]
I built the package using the steps listed in the documentation but facing this error in spite of changing the log4j properties file. Here is the error description : 

`log4j:WARN No appenders could be found for logger (org.apache.kafka.connect.mongo.tools.ImportJob).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.Collections$SingletonList.get(Collections.java:4815)
        at org.apache.kafka.connect.mongo.tools.ImportDB.<init>(ImportData.kt:119)
        at org.apache.kafka.connect.mongo.tools.ImportJob.start(ImportData.kt:56)
        at org.apache.kafka.connect.mongo.tools.ImportDataKt.main(ImportData.kt:260)`

Could you help me out with this?

**Comment by sailxjx** [comment]
@harshsp31 What does your log file look like?
